name: MacOS Build

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install ck
      run:  brew update; brew install -v concurrencykit@0.7.0;
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - name: make test
      run: make test
